name: Update Chrome Extension

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters
on:
  push:
    branches:
      - main

jobs:
  # building
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install & build dist
        run: npm install && npm run build
      # ..
      - name: Zip
        run: |
          zip -r chrome-extension.zip dist -x '*.git*'


  # publishing
  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      # you can optionally specify extension ID here, we do this so that
      # all of our environments (dev, staging, prod) have a consistent ID
      # we can reference. Otherwise the extension ID is autogenerated.
      EXTENSION_ID: ${{ secrets.EXTENSION_ID }}

    steps:
      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: |
          chrome-webstore-upload upload --source chrome-extension.zip --auto-publish
        env:
          EXTENSION_ID: goecnpeohpdpecpaiobjeclendfhnlmj
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
